package logic;

/**
 * 
 * The interface for PCG algorithms.
 * 
 * @author Michael Bowes
 * 
 */
public interface ProceduralAlgorithm {

	/**
	 * Getter for the name of an algorithm.
	 *
	 * @return the name of the algorithm.
	 */
	String getName();

	/**
	 * 
	 * @return The map generated by the algorithm.
	 */
	int[][] getMap();

	/**
	 * Validates if a map has already been generated by the algorithm. Should be
	 * checked before fields of the algorithm are accessed.
	 * 
	 * @return
	 */
	boolean mapPresent();

	/**
	 * Generates a new map of the given size.
	 * 
	 * @return
	 */
	int[][] generateMap(int size);
}